### ISSUE TITLE
errors on coreclrhost.h (dotnet core)

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#41]
```
[1] laeeth@sheldrake> cat coreclrhost.dpp                                                     /tank2/develop/dotnetcore
#include "coreclrhost.h"

 // For each hosting API, we define a function prototype and a function pointer
// The prototype is useful for implicit linking against the dynamic coreclr
// library and the pointer for explicit dynamic loading (dlopen, LoadLibrary)
//
#define CORECLR_HOSTING_API(function, ...) extern "C" int function(__VA_ARGS__); typedef int (*function##_ptr)(__VA_ARGS__)
    
CORECLR_HOSTING_API(coreclr_initialize, const char* exePath, const char* appDomainFriendlyName, int propertyCount, const char** propertyKeys, const char** propertyValues, void** hostHandle, unsigned int* domainId);
CORECLR_HOSTING_API(coreclr_shutdown,
            void* hostHandle,
            unsigned int domainId);

CORECLR_HOSTING_API(coreclr_shutdown_2,
            void* hostHandle,
            unsigned int domainId,
            int* latchedExitCode);

CORECLR_HOSTING_API(coreclr_create_delegate,
            void* hostHandle,
            unsigned int domainId,
            const char* entryPointAssemblyName,
            const char* entryPointTypeName,
            const char* entryPointMethodName,
            void** delegate);

CORECLR_HOSTING_API(coreclr_execute_assembly,
            void* hostHandle,
            unsigned int domainId,
            int argc,
            const char** argv,
            const char* managedAssemblyPath,
        unsigned int* exitCode);

laeeth@sheldrake> g++ coreclrhost.h                                                           /tank2/develop/dotnetcore
laeeth@sheldrake> d++ --keep-d-files --print-cursors coreclrhost.dpp                          /tank2/develop/dotnetcore
Error: Error parsing 'coreclrhost.h':
error: expected identifier or '('
error: expected identifier or '('
error: expected identifier or '('
error: expected identifier or '('
error: expected identifier or '('

```

**Comment by burner** [comment]
```c
#define CORECLR_HOSTING_API(function, ...) \
    extern "C" int function(__VA_ARGS__); \
    typedef int (*function##_ptr)(__VA_ARGS__)

CORECLR_HOSTING_API(coreclr_shutdown,
            void* hostHandle,
            unsigned int domainId);
```

removing the extern "C" makes it compile

**Comment by burner** [comment]
```c
#define CORECLR_HOSTING_API(function, ...) extern "C" int function(__VA_ARGS__); typedef int (*function##_ptr)(__VA_ARGS__)

CORECLR_HOSTING_API(coreclr_shutdown, void* hostHandle, unsigned int domainId);
```
works with clang++, whitespace seems to matter

**Comment by atilaneves** [comment]
Fixed by [this commit](https://github.com/atilaneves/dpp/commit/cab63d1699630ee7d12f804c5767133703401fb8).

**Comment by Laeeth** [comment]
It's not fixed...

(dmd-2.080.0)laeeth@travel-engine> d++ --include-path ./coreclr/hosts/inc coreclrhost.dpp 
Error: Error parsing '/tmp/fileAceHMe':
/home/laeeth/coreclr/coreclr/src/./coreclr/hosts/inc/coreclrhost.h:19:1: error: expected identifier or '('
/home/laeeth/coreclr/coreclr/src/./coreclr/hosts/inc/coreclrhost.h:28:1: error: expected identifier or '('
/home/laeeth/coreclr/coreclr/src/./coreclr/hosts/inc/coreclrhost.h:32:1: error: expected identifier or '('
/home/laeeth/coreclr/coreclr/src/./coreclr/hosts/inc/coreclrhost.h:37:1: error: expected identifier or '('
/home/laeeth/coreclr/coreclr/src/./coreclr/hosts/inc/coreclrhost.h:45:1: error: expected identifier or '('

(dmd-2.080.0)[1] laeeth@travel-engine> cat coreclrhost.dpp                        ~/coreclr/coreclr/src
#include <coreclrhost.h>
@atilaneves

**Comment by atilaneves** [comment]
It's a C++ header with a `.h` extension - you have to use the `--parse-as-cpp` option of dpp.

**Comment by Laeeth** [comment]
ok - thanks
